def build_evidence_record(
    variant_id: str,
    gene: str,
    hgvs: str,
    phenotype: str,
    aliases: str = "",
    clinvar: ClinVarBulk | None = None,
    pubmed_candidates: int = DEFAULT_PUBMED_CANDIDATES,
) -> dict[str, Any]:
    query_base = f"{gene} {hgvs}".strip()
    query_full = f"{query_base} {phenotype}".strip() if phenotype else query_base

    if clinvar is not None:
        clinvar_result = clinvar.lookup(gene, hgvs)
    else:
        clinvar_result = {"variation_id": None, "pmids": [], "summary": {}}

    variation_id = clinvar_result["variation_id"]
    clinvar_pmids = clinvar_result["pmids"]
    summary = clinvar_result["summary"]

    aliases_list = _split_aliases(aliases)
    tokens = variant_tokens(hgvs, aliases_list)

    reference_pmids: list[str] = []
    titles: dict[str, str] = {}
    abstracts: dict[str, str] = {}
    years: dict[str, int] = {}

    if clinvar_pmids:
        clinvar_passages = fetch_articles(clinvar_pmids)
        by_pmid = {p.pmid: p for p in clinvar_passages if p.pmid}
        for pmid in clinvar_pmids:
            passage = by_pmid.get(pmid)
            if passage is None:
                continue
            if passage.title:
                titles[pmid] = passage.title
            if passage.abstract:
                abstracts[pmid] = passage.abstract
            if passage.year is not None:
                years[pmid] = passage.year
            if is_reference_passage(passage, tokens):
                reference_pmids.append(pmid)

    candidate_passages = fetch_pubmed_candidates(query_full, pubmed_candidates)
    pubmed_candidate_pmids: list[str] = []
    for passage in candidate_passages:
        pmid = passage.pmid
        if not pmid:
            continue
        if pmid not in titles and passage.title:
            titles[pmid] = passage.title
        if pmid not in abstracts and passage.abstract:
            abstracts[pmid] = passage.abstract
        if passage.year is not None and pmid not in years:
            years[pmid] = passage.year
        pubmed_candidate_pmids.append(pmid)

    candidate_pmids: list[str] = []
    seen: set[str] = set()
    for pmid in clinvar_pmids + pubmed_candidate_pmids:
        if pmid and pmid not in seen:
            seen.add(pmid)
            candidate_pmids.append(pmid)

    return {
        "variant_id": variant_id,
        "gene": gene,
        "hgvs": hgvs,
        "query": query_full,
        "aliases": aliases_list,
        "clinvar_variation_id": variation_id,
        "clinvar_summary": summary,
        "clinvar_linked_pmids": clinvar_pmids,
        "clinvar_found": variation_id is not None,
        "reference_pmids": reference_pmids,
        "pubmed_candidate_pmids": pubmed_candidate_pmids,
        "candidate_pmids": candidate_pmids,
        "titles": titles,
        "abstracts": abstracts,
        "years": years,
        "label_source": "ClinVar-linked citations filtered by variant token and aliases",
        "candidate_source": "ClinVar bulk and PubMed esearch",
        "notes": "auto-generated by prepare_golden_evidence",
    }
